add mobile menu
Dmytr0-kova1/YachtJet-proj-04 pull request #4
Opened 2024-08-08 19:03 UTC by DarkLordSith

pls check js connection too

2024-08-08 19:44 UTC, Dmytr0-kova1 requested changes
сама кнопка close на макеті більша, і зроби медіа правило щоб на планшеті менюшка пропадала

2024-08-08 19:44 UTC, Dmytr0-kova1 commented on src/css/mob_menu.css
> +  font-family: 'Inter', sans-serif;
не потрібно дублювати шрифт

2024-08-08 19:57 UTC, Dmytr0-kova1 approved these changes

2024-08-08 19:58 UTC, merged

2024-08-09 07:06 UTC, DarkLordSith commented on src/css/mob_menu.css
> +  font-family: 'Inter', sans-serif;
ok, in process