add markup and styles
Dmytr0-kova1/YachtJet-proj-04 pull request #8
Opened 2024-08-09 13:47 UTC by svitlana-verkhomii1983

Фото відображаються у поганій якості.

2024-08-09 17:43 UTC, Dmytr0-kova1 requested changes
спробуйте завантажити картинки у форматі png

2024-08-09 18:30 UTC, svitlana-verkhomii1983 commented
Змінила фото на формат png  (вони оптимізовані).

2024-08-09 19:21 UTC, Dmytr0-kova1 requested changes
поставте будь ласка на діви правило css ""margin: 0 auto;""

2024-08-09 19:21 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +    background-color: #0e1823;
приберіть дублювання коду

2024-08-09 19:21 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +    color: #fbfbfb;
приберіть дублювання коду

2024-08-09 19:21 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +    color: #fbfbfb;
приберіть дублювання коду

2024-08-09 19:21 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +        width: 768px;
приберіть дублювання коду

2024-08-09 19:21 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +        padding-left: 32px;
це теж наразі приберіть

2024-08-09 19:21 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +        padding-right: 32px;
це теж наразі приберіть

2024-08-09 19:21 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +        width: 1280px;
приберіть дублювання коду

2024-08-09 19:21 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +        padding-right: 50px;
падінги теж наразі приберіть

2024-08-10 08:58 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +    color: #fbfbfb;
Дмитро, line-height: 1.17 - я залишаю, тому що це стилі для тексту і ніде раніше цей параметр у мене не заданий.

2024-08-10 09:00 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +    background-color: #0e1823;
Прибрала

2024-08-10 09:01 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +    color: #fbfbfb;
Дмитро, line-height: 1 та font-size: 28px - я залишаю, тому що це стилі саме для цього тексту. Інше - прибрала.

2024-08-10 09:03 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +        width: 768px;
Прибрала

2024-08-10 09:03 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +        padding-left: 32px;
Прибрала

2024-08-10 09:04 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +        padding-right: 32px;
Прибрала

2024-08-10 09:04 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +        width: 1280px;
Прибрала

2024-08-10 09:04 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +        padding-right: 50px;
Прибрала

2024-08-10 09:11 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +        padding-right: 50px;
Що стосовно фото? Залишаю, як є?

2024-08-10 10:14 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +        padding-right: 50px;
Перша картка у мобільній версії не стоїть по центру. Підкажіть, будь ласка, як виправити ситуацію. До редагування коду вона стояла по центру. Дякую.

2024-08-10 10:22 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +    color: #fbfbfb;
тут потрібно прибрати тількі color: #fbfbfb;

2024-08-10 10:24 UTC, Dmytr0-kova1 commented on src/css/reviews.css
> +    color: #fbfbfb;
цей коментар тільки для рядка 19

2024-08-10 11:01 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +    color: #fbfbfb;
Добре, але вказуйте це одразу, ок? Бо тут вказані 4 стилі

2024-08-10 11:03 UTC, svitlana-verkhomii1983 commented on src/css/reviews.css
> +    color: #fbfbfb;
Добре

2024-08-10 11:25 UTC, Dmytr0-kova1 approved these changes

2024-08-10 11:25 UTC, merged